# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/j/cmake-4.0.2-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/j/cmake-4.0.2-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/j/projects/ubi-2025/engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/j/projects/ubi-2025/engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/home/j/cmake-4.0.2-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/j/cmake-4.0.2-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/j/projects/ubi-2025/engine/CMakeFiles /home/j/projects/ubi-2025/engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/j/projects/ubi-2025/engine/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/j/projects/ubi-2025/engine/CMakeFiles /home/j/projects/ubi-2025/engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/j/projects/ubi-2025/engine/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ContestAPI

# Build rule for target.
ContestAPI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContestAPI
.PHONY : ContestAPI

# fast build rule for target.
ContestAPI/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/build
.PHONY : ContestAPI/fast

#=============================================================================
# Target rules for targets named Game

# Build rule for target.
Game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Game
.PHONY : Game

# fast build rule for target.
Game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/build
.PHONY : Game/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

src/ContestAPI/SimpleController.o: src/ContestAPI/SimpleController.cpp.o
.PHONY : src/ContestAPI/SimpleController.o

# target to build an object file
src/ContestAPI/SimpleController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/SimpleController.cpp.o
.PHONY : src/ContestAPI/SimpleController.cpp.o

src/ContestAPI/SimpleController.i: src/ContestAPI/SimpleController.cpp.i
.PHONY : src/ContestAPI/SimpleController.i

# target to preprocess a source file
src/ContestAPI/SimpleController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/SimpleController.cpp.i
.PHONY : src/ContestAPI/SimpleController.cpp.i

src/ContestAPI/SimpleController.s: src/ContestAPI/SimpleController.cpp.s
.PHONY : src/ContestAPI/SimpleController.s

# target to generate assembly for a file
src/ContestAPI/SimpleController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/SimpleController.cpp.s
.PHONY : src/ContestAPI/SimpleController.cpp.s

src/ContestAPI/SimpleSound.o: src/ContestAPI/SimpleSound.cpp.o
.PHONY : src/ContestAPI/SimpleSound.o

# target to build an object file
src/ContestAPI/SimpleSound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/SimpleSound.cpp.o
.PHONY : src/ContestAPI/SimpleSound.cpp.o

src/ContestAPI/SimpleSound.i: src/ContestAPI/SimpleSound.cpp.i
.PHONY : src/ContestAPI/SimpleSound.i

# target to preprocess a source file
src/ContestAPI/SimpleSound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/SimpleSound.cpp.i
.PHONY : src/ContestAPI/SimpleSound.cpp.i

src/ContestAPI/SimpleSound.s: src/ContestAPI/SimpleSound.cpp.s
.PHONY : src/ContestAPI/SimpleSound.s

# target to generate assembly for a file
src/ContestAPI/SimpleSound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/SimpleSound.cpp.s
.PHONY : src/ContestAPI/SimpleSound.cpp.s

src/ContestAPI/SimpleSprite.o: src/ContestAPI/SimpleSprite.cpp.o
.PHONY : src/ContestAPI/SimpleSprite.o

# target to build an object file
src/ContestAPI/SimpleSprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/SimpleSprite.cpp.o
.PHONY : src/ContestAPI/SimpleSprite.cpp.o

src/ContestAPI/SimpleSprite.i: src/ContestAPI/SimpleSprite.cpp.i
.PHONY : src/ContestAPI/SimpleSprite.i

# target to preprocess a source file
src/ContestAPI/SimpleSprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/SimpleSprite.cpp.i
.PHONY : src/ContestAPI/SimpleSprite.cpp.i

src/ContestAPI/SimpleSprite.s: src/ContestAPI/SimpleSprite.cpp.s
.PHONY : src/ContestAPI/SimpleSprite.s

# target to generate assembly for a file
src/ContestAPI/SimpleSprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/SimpleSprite.cpp.s
.PHONY : src/ContestAPI/SimpleSprite.cpp.s

src/ContestAPI/app.o: src/ContestAPI/app.cpp.o
.PHONY : src/ContestAPI/app.o

# target to build an object file
src/ContestAPI/app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/app.cpp.o
.PHONY : src/ContestAPI/app.cpp.o

src/ContestAPI/app.i: src/ContestAPI/app.cpp.i
.PHONY : src/ContestAPI/app.i

# target to preprocess a source file
src/ContestAPI/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/app.cpp.i
.PHONY : src/ContestAPI/app.cpp.i

src/ContestAPI/app.s: src/ContestAPI/app.cpp.s
.PHONY : src/ContestAPI/app.s

# target to generate assembly for a file
src/ContestAPI/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/app.cpp.s
.PHONY : src/ContestAPI/app.cpp.s

src/ContestAPI/main.o: src/ContestAPI/main.cpp.o
.PHONY : src/ContestAPI/main.o

# target to build an object file
src/ContestAPI/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/main.cpp.o
.PHONY : src/ContestAPI/main.cpp.o

src/ContestAPI/main.i: src/ContestAPI/main.cpp.i
.PHONY : src/ContestAPI/main.i

# target to preprocess a source file
src/ContestAPI/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/main.cpp.i
.PHONY : src/ContestAPI/main.cpp.i

src/ContestAPI/main.s: src/ContestAPI/main.cpp.s
.PHONY : src/ContestAPI/main.s

# target to generate assembly for a file
src/ContestAPI/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/main.cpp.s
.PHONY : src/ContestAPI/main.cpp.s

src/ContestAPI/vendor/miniaudio/miniaudio.o: src/ContestAPI/vendor/miniaudio/miniaudio.cpp.o
.PHONY : src/ContestAPI/vendor/miniaudio/miniaudio.o

# target to build an object file
src/ContestAPI/vendor/miniaudio/miniaudio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/vendor/miniaudio/miniaudio.cpp.o
.PHONY : src/ContestAPI/vendor/miniaudio/miniaudio.cpp.o

src/ContestAPI/vendor/miniaudio/miniaudio.i: src/ContestAPI/vendor/miniaudio/miniaudio.cpp.i
.PHONY : src/ContestAPI/vendor/miniaudio/miniaudio.i

# target to preprocess a source file
src/ContestAPI/vendor/miniaudio/miniaudio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/vendor/miniaudio/miniaudio.cpp.i
.PHONY : src/ContestAPI/vendor/miniaudio/miniaudio.cpp.i

src/ContestAPI/vendor/miniaudio/miniaudio.s: src/ContestAPI/vendor/miniaudio/miniaudio.cpp.s
.PHONY : src/ContestAPI/vendor/miniaudio/miniaudio.s

# target to generate assembly for a file
src/ContestAPI/vendor/miniaudio/miniaudio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/vendor/miniaudio/miniaudio.cpp.s
.PHONY : src/ContestAPI/vendor/miniaudio/miniaudio.cpp.s

src/ContestAPI/vendor/stb_image/stb_image.o: src/ContestAPI/vendor/stb_image/stb_image.cpp.o
.PHONY : src/ContestAPI/vendor/stb_image/stb_image.o

# target to build an object file
src/ContestAPI/vendor/stb_image/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/vendor/stb_image/stb_image.cpp.o
.PHONY : src/ContestAPI/vendor/stb_image/stb_image.cpp.o

src/ContestAPI/vendor/stb_image/stb_image.i: src/ContestAPI/vendor/stb_image/stb_image.cpp.i
.PHONY : src/ContestAPI/vendor/stb_image/stb_image.i

# target to preprocess a source file
src/ContestAPI/vendor/stb_image/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/vendor/stb_image/stb_image.cpp.i
.PHONY : src/ContestAPI/vendor/stb_image/stb_image.cpp.i

src/ContestAPI/vendor/stb_image/stb_image.s: src/ContestAPI/vendor/stb_image/stb_image.cpp.s
.PHONY : src/ContestAPI/vendor/stb_image/stb_image.s

# target to generate assembly for a file
src/ContestAPI/vendor/stb_image/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContestAPI.dir/build.make CMakeFiles/ContestAPI.dir/src/ContestAPI/vendor/stb_image/stb_image.cpp.s
.PHONY : src/ContestAPI/vendor/stb_image/stb_image.cpp.s

src/Game/GameTest.o: src/Game/GameTest.cpp.o
.PHONY : src/Game/GameTest.o

# target to build an object file
src/Game/GameTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/src/Game/GameTest.cpp.o
.PHONY : src/Game/GameTest.cpp.o

src/Game/GameTest.i: src/Game/GameTest.cpp.i
.PHONY : src/Game/GameTest.i

# target to preprocess a source file
src/Game/GameTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/src/Game/GameTest.cpp.i
.PHONY : src/Game/GameTest.cpp.i

src/Game/GameTest.s: src/Game/GameTest.cpp.s
.PHONY : src/Game/GameTest.s

# target to generate assembly for a file
src/Game/GameTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/src/Game/GameTest.cpp.s
.PHONY : src/Game/GameTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... ContestAPI"
	@echo "... Game"
	@echo "... src/ContestAPI/SimpleController.o"
	@echo "... src/ContestAPI/SimpleController.i"
	@echo "... src/ContestAPI/SimpleController.s"
	@echo "... src/ContestAPI/SimpleSound.o"
	@echo "... src/ContestAPI/SimpleSound.i"
	@echo "... src/ContestAPI/SimpleSound.s"
	@echo "... src/ContestAPI/SimpleSprite.o"
	@echo "... src/ContestAPI/SimpleSprite.i"
	@echo "... src/ContestAPI/SimpleSprite.s"
	@echo "... src/ContestAPI/app.o"
	@echo "... src/ContestAPI/app.i"
	@echo "... src/ContestAPI/app.s"
	@echo "... src/ContestAPI/main.o"
	@echo "... src/ContestAPI/main.i"
	@echo "... src/ContestAPI/main.s"
	@echo "... src/ContestAPI/vendor/miniaudio/miniaudio.o"
	@echo "... src/ContestAPI/vendor/miniaudio/miniaudio.i"
	@echo "... src/ContestAPI/vendor/miniaudio/miniaudio.s"
	@echo "... src/ContestAPI/vendor/stb_image/stb_image.o"
	@echo "... src/ContestAPI/vendor/stb_image/stb_image.i"
	@echo "... src/ContestAPI/vendor/stb_image/stb_image.s"
	@echo "... src/Game/GameTest.o"
	@echo "... src/Game/GameTest.i"
	@echo "... src/Game/GameTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

